version: "3.9"

services:
  vpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./volumes/vpn/conf:/etc/openvpn
    networks:
      private_net:
        ipv4_address: 172.16.10.2

  external_webserver:
    build: docker/webserver
    hostname: host-prod-a
    expose:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8088"
      - "21"
    networks:
      private_net:
        ipv4_address: 172.16.10.4

  internal_webserver:
    build: docker/webserver
    hostname: host-prod-b
    expose:
      - "80"
      - "22"
    networks:
      private_net:
        ipv4_address: 172.16.10.5
    
  db:
    image: postgres
    restart: always
    hostname: db-prod-a
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my_secret_example_password
    expose:
      - "5432"
    networks:
      private_net:
        ipv4_address: 172.16.10.6

  dev_laptop_1:
    build: docker/dev_laptop
    restart: always
    hostname: alice
    networks:
      private_net:
        ipv4_address: 172.16.10.100

  dev_laptop_2:
    build: docker/dev_laptop
    restart: always
    hostname: bob
    networks:
      private_net:
        ipv4_address: 172.16.10.101

  camera_1:
    build: docker/camera
    restart: always 
    hostname: cam1 
    expose:
      - "80"
    volumes:
      - ./volumes/camera/feed_1:/usr/local/apache2/htdocs/feed
    networks:
      private_net:
        ipv4_address: 172.16.10.200

  camera_2:
    build: docker/camera
    restart: always 
    hostname: cam1 
    expose:
      - "80"
    volumes:
      - ./volumes/camera/feed_2:/usr/local/apache2/htdocs/feed
    networks:
      private_net:
        ipv4_address: 172.16.10.201

  camera_3:
    build: docker/camera
    restart: always 
    hostname: cam1 
    expose:
      - "80"
    volumes:
      - ./volumes/camera/feed_3:/usr/local/apache2/htdocs/feed
    networks:
      private_net:
        ipv4_address: 172.16.10.202

networks:
  private_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24
          gateway: 172.16.10.1