version: "3.9"

services:
  vpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: vpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-config/conf:/etc/openvpn
    networks:
      - internal

  webapp:
    build: webapp
    hostname: host-prod-a
    expose:
      - "80"
      - "22"
    networks:
      - internal
    
  db:
    image: postgres
    restart: always
    hostname: db-prod-a
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my_secret_example_password
    expose:
      - "5432"
    networks:
      - internal

networks:
  internal:
    ipam:
      config:
        - subnet: 172.20.0.0/16