version: "3.9"

services:
  vpn:
    image: kylemanna/openvpn
    hostname: vpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./volumes/vpn/conf:/etc/openvpn
    networks:
      private_net:
        ipv4_address: 172.16.10.2

  external_webserver:
    build: docker/webserver
    hostname: host-prod-a
    environment:
      - USERS=bob:password;alice:password
    expose:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8088"
      - "23"
    volumes:
      - ./volumes/website_prod:/usr/local/apache2/htdocs/prod
      - ./volumes/website_staging:/usr/local/apache2/htdocs/staging
    networks:
      private_net:
        ipv4_address: 172.16.10.4

  internal_webserver:
    build: docker/webserver
    hostname: host-prod-b
    expose:
      - "80"
      - "23"
    volumes:
      - ./volumes/website_internal:/usr/local/apache2/htdocs/prod
    networks:
      private_net:
        ipv4_address: 172.16.10.5
    
  db:
    image: postgres
    restart: always
    hostname: db-prod-a
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example_test_password
    expose:
      - "5432"
    networks:
      private_net:
        ipv4_address: 172.16.10.6

  dev_laptop_1:
    build: docker/dev_laptop
    restart: always
    hostname: alice
    volumes:
      - ./volumes/users/alice:/usr/local/automation
    networks:
      private_net:
        ipv4_address: 172.16.10.121

  dev_laptop_2:
    build: docker/dev_laptop
    restart: always
    hostname: bob
    volumes:
      - ./volumes/users/bob:/usr/local/automation
    networks:
      private_net:
        ipv4_address: 172.16.10.122

  camera_1:
    build: docker/camera
    restart: always 
    hostname: cam1
    expose:
      - "80"
    volumes:
      - ./volumes/cameras/feed_1.jpg:/usr/local/apache2/htdocs/feed.jpg
    networks:
      private_net:
        ipv4_address: 172.16.10.223

  camera_2:
    build: docker/camera
    restart: always 
    hostname: cam2
    expose:
      - "80"
    volumes:
      - ./volumes/cameras/feed_2.jpg:/usr/local/apache2/htdocs/feed.jpg
    networks:
      private_net:
        ipv4_address: 172.16.10.224

  camera_3:
    build: docker/camera
    restart: always 
    hostname: cam3
    expose:
      - "80"
    volumes:
      - ./volumes/cameras/feed_3.jpg:/usr/local/apache2/htdocs/feed.jpg
    networks:
      private_net:
        ipv4_address: 172.16.10.225

networks:
  private_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24
          gateway: 172.16.10.1